// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109173105_idOrder")]
    partial class idOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("externalId")
                        .HasColumnType("char(36)");

                    b.Property<int>("idOrder")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("payments");
                });
#pragma warning restore 612, 618
        }
    }
}
